# Generated by Django 5.0.4 on 2024-04-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='porfolio/image3/')),
            ],
        ),
    ]
